### PR TITLE
Create lp_NoiseDistort

### PR DESCRIPTION
**Pull request by CameraRick**
This PyPlug can be used to quickly add noise-based distortion to a plate. This is a great way to give some life to e.g. trees in a background image (works best with amplified animation, distortion and applied defocus)

Two noise layer are used to give some fluid motion over time; the layers are completely customizable in appereance (including rotation and aspect ratio), most values even individually for each noise layer. Features comfort-options like a mask-input and layer-preview options.

The PyPlug is setup to animate over time be default, but can also easily be animated by hand.

http://i.giphy.com/3o6Zt4kIvpXiiQx8J2.gif

### CODE REVIEW

**Comment by olear** [comment]
Great, make you a member so you can push directly to this repository if wanted.

**Comment by CameraRick** [comment]
I really don't understand any of this I just Click Buttons, but it seems to 
work (to a degree) :o

Thank you for assisting :)

mobil gesendet || sent from mobile



Am 28. September 2016 11:46:23 nachm. schrieb Ole-André Rodlie 
<notifications@github.com>:

**Comment by olear** [comment]
This works, the important part is that you are able to contribute.

Happy to assist :)

**Comment by CameraRick** [comment]
First Open source project I'm contributing to because I actually CAN 
contribute something aside of lame critique :)

Have a good night,
Lucas

mobil gesendet || sent from mobile



Am 29. September 2016 12:02:36 vorm. schrieb Ole-André Rodlie 
<notifications@github.com>:

**Comment by olear** [comment]
added a quick and dirty git howto: https://github.com/NatronVFX/natron-plugins/wiki/useGit

I also think there exists some GUI frontend for git, but I have never tried any.

**Comment by CameraRick** [comment]
I actually downloaded the GUI yesterday after I asked a friend how to use 
GitHub, and he told me that the Website is not so good. I downloaded it and 
I really didn't get how to do anything there, haha :) so I used the Website 
entirely, at least I understood a bit better what I did there.
I mean even with a GUI, you have to actually know what steps you need to 
do, as non-user I had a hard time imagine where I can add (not edit) 
things. The Buttons on the Webportal were helpful here :)


mobil gesendet || sent from mobile



Am 29. September 2016 12:52:54 vorm. schrieb Ole-André Rodlie 
<notifications@github.com>:

**Comment by sozap** [comment]
Cool ! thanks for the Howto @olear it will help me to get more into Github ! 
@CameraRick first times with gihub was a bit painful for me but the pain don't stay that long, it's even getting on the pleasure side with time !

**Comment by CameraRick** [comment]
Haha I only answered on emails I had no idea this was public :)

I'll try to get used to it, hopefully one day I can do everything myself :)

**Pull request merged**
